Feature/augment answers (#41)
tensorplex-labs/dojo-synthetic-api pull request #43
Opened 2024-11-22 04:53 UTC by mediumsizeworkingdog

* enabled generation of both question augmented and answer augmented tasks
* replaced sonnet with haiku for question and answer generation
* enabled token tracing to calculate cost of using non-openAI and non-claude models on langfuse
* removal of dead code and stylistic refactors

2024-12-02 06:59 UTC, jarvis8x7b commented on commons/synthetic.py
> +        "output_cost": None,
btw would this still log the cost correctly on the dashboard?

2024-12-02 06:59 UTC, jarvis8x7b commented on commons/synthetic.py
> +def _merge_JS_and_HTML(result):
maybe use all lowercase

2024-12-02 06:59 UTC, jarvis8x7b commented on commons/synthetic.py
> +    answer_models = random.choice(ANSWER_MODELS)
should we clean this up to be just a string, since we always use a list of 1 elem

2024-12-02 07:09 UTC, mediumsizeworkingdog commented on commons/synthetic.py
> +    answer_models = random.choice(ANSWER_MODELS)
we could. We are using a list rn because our old implementation was using multiple random models to answer the same question prompt

2025-01-08 11:32 UTC, jarvis8x7b requested changes
blocking this as dojo dependencies not ready atm

2025-04-15 10:43 UTC, jarvis8x7b approved these changes

2025-04-16 15:35 UTC, merged